---
# Handlers for MongoDB

- name: restart mongo
  command: docker restart mongo

- name: start mongo
  command: docker start mongo

- name: stop mongo
  command: docker stop mongo

- name: rm mongo
  command: docker rm mongo

- name: pull mongo
  command: docker pull mongo

- name: run mongo
  command: docker run --name mongo -v /mnt/sda1/opt/mongo:/data/db -p 27017:27017 -d mongo